
services:
  mongo:
    image: mongo
    container_name: achamigos-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: achamigos-backend
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/achamigos
      - LOGTAIL_SOURCE_TOKEN=h9sCAQmdLY5CoZDz38AxqJ5q
      - GEMINI_API_KEY=AIzaSyCYmFalzucOov6hmTBoLjgXeTN2dgKHJi0
      - API_KEY=1234

volumes:
  mongo_data: