sonar.projectKey=achamigos-backend
sonar.organization=luanzeraa-lab

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts
sonar.exclusions=node_modules/**

<<<<<<< HEAD

sonar.javascript.lcov.reportPaths=coverage/lcov.info
=======
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
>>>>>>> develop

sonar.javascript.lcov.reportPaths=coverage/lcov.info