sonar.projectKey=achamigos-backend
sonar.organization=luanzeraa-lab

sonar.sources=.
sonar.inclusions=src/**/*.ts, controllers/**/*.ts, models/**/*.ts, services/**/*.ts, routes/**/*.ts, middleware/**/*.ts, utils/**/*.ts, config/**/*.ts

sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts
sonar.coverage.exclusions=**/*.spec.ts, **/*.test.ts, node_modules/**, dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info